config/routes.rb
Rails.application.routes.draw do

  # admin
  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :products,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'products#top'
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

   # customer
   devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
   }

  get 'about' => 'customer/products#about'
  root 'customer/products#top'
  get 'contact' => 'customer/customers#contact'

  scope module: :customer do
    resources :products,only: [:index,:show]
    get 'search' => 'products#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :shipping_addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_address, dependent: :destroy
  has_many :orders
  has_many :cart_items, dependent: :destroy

  validates :first_name, :last_name, :kana_first_name, :kana_last_name,
            :residence, :phone_number,
            presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :phone_number, numericality: { only_integer: true }
  validates :kana_first_name, :kana_last_name,
      format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "カタカナで入力して下さい。"}

  # 退会機能
  def active_for_authentication?
    super && (self.is_valid == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
	end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:residence,:phone_number,:email,:is_valid)
	end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  include ApplicationHelper

  before_action :set_cart_item, only: [:update, :destroy]
  before_action :authenticate_customer!

  def index
    @cart_items = current_cart
  end

	def update
    @cart_item.update(quantity: params[:cart_item][:quantity].to_i)
    flash.now[:success] = "#{@cart_item.product.name}の数量を変更しました"
    @price = sub_price(@cart_item).to_s(:delimited)
    @cart_items = current_cart
    @total = total_price(@cart_items).to_s(:delimited)
    # redirect_to customers_cart_items_path
	end

	def create
    @cart_item = current_customer.cart_items.new(params_cart_item)

      # カートの中に同じ商品が重複しないようにして　古い商品と新しい商品の数量を合わせる
    @update_cart_item =  CartItem.find_by(product: @cart_item.product)
    if @update_cart_item.present? && @cart_item.valid?
        @cart_item.quantity += @update_cart_item.quantity
        @update_cart_item.destroy
    end

    if @cart_item.save
      flash[:notice] = "#{@cart_item.product.name}をカートに追加しました"
      redirect_to products_path
    else
      @product = Product.find(params[:cart_item][:product_id])
      @cart_item = CartItem.new
      flash[:alert] = "個数を選択してください"
      render ("customer/products/show")
    end
	end

	def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:alert] = "カートの商品を全て削除しました"
    redirect_to customers_cart_items_path
	end

	def destroy
    @cart_item.destroy
    flash.now[:alert] = "#{@cart_item.product.name}を削除しました"
    @cart_items = current_cart
    @total = total_price(@cart_items).to_s(:delimited)
    # respond_to do |format|
    #   format.html{ redirect_to customers_cart_items_path }
    #   format.js
    # end
    # redirect_to customers_cart_items_path
	end

  private

  def params_cart_item
    params.require(:cart_item).permit(:quantity, :product_id)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController

  before_action :authenticate_customer!, except: [:contact]

  def show
    @customer = current_customer
	end

	def quit
	end

	def out
    @customer = current_customer
    @customer.update(is_valid: true)

    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
	end

	def edit
    @customer = current_customer
	end

	def update
    @customer = current_customer
		if @customer.update(customer_params)
       flash[:success] = "登録情報を変更しました"
       redirect_to customers_path
    else
       render :edit and return
    end
	end

  def contact
  end

	private

	def customer_params
  	params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :postal_code, :residence, :phone_numbar)
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  include ApplicationHelper

  before_action :to_log, only: [:show]
  before_action :authenticate_customer!

  def new
  	@order = Order.new
  	@shipping_addresses = ShippingAddress.where(customer: current_customer)
	end

	def log
    @cart_items = current_cart
		@order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method]
    )

    # total_priceに請求額を代入
    @order.total_price = billing(@order)

    # addressにresidenceの値がはいっていれば
    if params[:order][:addresses] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.residence
      @order.name        = current_customer.last_name +
                           current_customer.first_name

    # addressにshipping_addressesの値がはいっていれば
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = ShippingAddress.find(params[:order][:shipping_address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
    elsif params[:order][:addresses] == "new_address"
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
      unless @order.valid? == true
        @shipping_addresses = ShippingAddress.where(customer: current_customer)
        render :new
      end
    end
	end

	def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to thanx_customers_orders_path

    # もし情報入力でnew_addressの場合ShippingAddressに保存
    if params[:order][:ship] == "1"
      current_customer.shipping_address.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    @cart_items = current_cart
    @cart_items.each do |cart_item|
    OrderDetail.create(
      product:  cart_item.product,
      order:    @order,
      quantity: cart_item.quantity,
      subprice: sub_price(cart_item)
    )
    end
    # 注文完了後、カート商品を空にする
    @cart_items.destroy_all
	end

	def thanx
	end

	def index
    @orders = current_customer.orders
	end

	def show
	  @order = Order.find(params[:id])
    @order_details = @order.order_details
	end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def to_log
    redirect_to customers_cart_items_path if params[:id] == "log"
  end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController

  before_action :authenticate_customer!, only: [:show]

  def top
    @products = Product.all.order(created_at: :asc)
    #=> :asc,古い順 :desc,新しい順　
    @genres = Genre.all
	end

	def index
    @genres = Genre.all
    @products = Product.where(is_sale: true).page(params[:page]).per(8)
	end

	def show
    @products = Product.all
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
	end

  def about
  end

	private
	def product_params
		parmas.require(:product).permit(:image ,:name, :explanation, :tax_out_price, :is_sale)
	end
  
end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController

  before_action :authenticate_customer!

  def index
  	@shipping_addresses = current_customer.shipping_address
  	@shipping_address = ShippingAddress.new
	end

	def create
	  @shipping_address = ShippingAddress.new(shipping_address_params)
	  @shipping_address.customer_id = current_customer.id
    @shipping_addresses = current_customer.shipping_address
	  if @shipping_address.save
	  	 flash.now[:notice] = "新規配送先を登録しました"
	     # redirect_to customers_shipping_addresses_path
	  # else
	  # 	 @shipping_addresses = current_customer.shipping_address
	  #    render 'index'
    end
	end

	def edit
    @shipping_address = ShippingAddress.find(params[:id])
	end

	def update
	  @shipping_address = ShippingAddress.find(params[:id])
	  if @shipping_address.update(shipping_address_params)
  	 flash[:success] = "配送先を変更しました"
     redirect_to customers_shipping_addresses_path
	  else
	   render "edit"
	  end
	end

	def destroy
	  @shipping_address = ShippingAddress.find(params[:id])
	  @shipping_address.destroy
    @shipping_addresses = current_customer.shipping_address
    flash.now[:alert] = "配送先を削除しました"
	  # redirect_to customers_shipping_addresses_path
	end

	private

	def shipping_address_params
  	params.require(:shipping_address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :authenticate_customer!, only: [:edit, :update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
     # @customer = current_customer
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      # respond_with resource, location: after_update_path_for(resource)
      flash[:success] = "パスワード変更しました。"
      redirect_to customers_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to customers_path
      flash[:alert] = "パスワードを変更できませんでした。"
    end
    # super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def customer_params
    params.require(:customers).permit(:password, :password_confirmation)
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation])
  # end

  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  def after_update_path_for(resource)
    customers_path(resource)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController

    before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_customer_session_path
      end
    else
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/helpers/customer/shipping_addresses_helper.rb
module Customer::ShippingAddressesHelper
end

app/views/customer/customers/contact.html.erb
<% provide(:title, "お問い合わせ") %>
<div class="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">お問い合わせ</h2>

    <%= form_with url:root_path do |f| %>

      <div class="col-xs-10">
        <div class="form-group col-xs-12">
          <%= f.label :"氏名", class: "col-sm-3 control-label" %>
          <%= f.text_field :name, class: "col-sm-4 form-control-static name" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"メールアドレス", class: "col-sm-3 control-label" %>
            <%= f.email_field :mail, autofocus: true, autocomplete: "email", class: "col-sm-9 form-control-static" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"お問い合わせ内容", class: "col-sm-3 control-label" %>
          <%= f.text_area :comment,class: "col-sm-9 form-control-static" %>
        </div>
        <div class="form-group col-xs-12 text-center">
          <p>気軽にお問い合わせください</P>
        </div>
        <div class="actions col-xs-8">
          <%= f.submit "送信する", class: "btn btn-primary col-sm-5 pull-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/customer/customers/edit.html.erb
<% provide(:title, "登録情報編集") %>
<div class="row">
  <div class="col-xs-12">

    <h2 class="head-line title_h2 text-center">登録情報編集</h2>

    <%= form_with(model:@customer, url:customer_path, local: true ,method: :put) do |f| %>

      <%= render "layouts/error_messages", resource: @customer %>

      <div class="col-xs-10">
        <div class="form-group col-xs-12">
          <%= f.label :"氏名", class: "col-sm-3 control-label" %>
          <%= f.text_field :last_name, class: "last_name col-sm-3 form-control-static name" %>
          <%= f.text_field :first_name, class: "first_name col-sm-3 form-control-static name" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"フリガナ", class: "col-sm-3 control-label" %>
          <%= f.text_field :kana_last_name, class: "kana_last_name col-sm-3 form-control-static name" %>
          <%= f.text_field :kana_first_name, class: "kana_first_name col-sm-3 form-control-static name" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"メールアドレス", class: "col-sm-3 control-label" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-sm-6 form-control-static" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"郵便番号", class: "col-sm-3 control-label" %>
          <%= f.text_field :postal_code, class: "col-sm-2 form-control-static" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"住所", class: "col-sm-3 control-label" %>
          <%= f.text_field :residence, class: "col-sm-9 form-control-static" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"電話番号(ハイフンなし)", class: "col-sm-3 control-label" %>
          <%= f.text_field :phone_number, class: "col-sm-2 form-control-static" %>
        </div>
      </div>

      <div class="actions col-xs-9 col-xs-offset-3">
        <%= f.submit "編集内容を保存する", class: "btn btn-primary save col-xs-6" %>
        <%= link_to '退会する', quit_customers_path, class: "glyphicon glyphicon-tint btn btn-danger"%>
      </div>
    <% end %>
    <div class="col-xs-12">
      <%= link_to "戻る", customers_path, class: "glyphicon glyphicon-home btn btn-info" %>
    </div>
  </div>
</div>

app/views/customer/customers/quit.html.erb
<% provide(:title, "退会ページ") %>
<div class="quit">
  <strong>本当に退会しますか？</strong>

    <div class="quit-msg">
      退会すると会員情報登録や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      <br>
      退会する場合は,「退会する」をクリックしてください。
    </div>

    <%= link_to "退会しない", customers_path, class: 'glyphicon glyphicon-home btn btn-primary' %>
    <%= link_to "退会する", out_customers_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: "glyphicon glyphicon-tint btn btn-danger" %>

</div>

app/views/customer/customers/show.html.erb
<% provide(:title, "マイページ") %>
<div class="row">
	<div class="col-xs-offset-1 col-xs-8">
		<h2 class="head-line text-center title_h2">マイページ</h2>
		<p><strong class="information-link"><i class="far fa-user"></i>登録情報</strong>
			<%= link_to " 編集する", customer_edit_path, class: "glyphicon glyphicon-pencil btn btn-success" %>
			<%= link_to " パスワードを変更する", edit_customer_registration_path, class: "glyphicon glyphicon-pencil btn btn-warning" %>
		</p>

			<table class="table table-bordered table-condensed" >
				<tbody>
					<tr>
						<td class="info col-xs-2">氏名</td>
						<td class="text-left"><%= full_name(@customer) %></td>
					</tr>
					<tr>
						<td class="info">カナ</td>
						<td class="text-left"><%= kana_full_name(@customer) %></td>
					</tr>
					<tr>
						<td class="info">郵便番号</td>
						<td class="text-left"><%= @customer.postal_code %></td>
					</tr>
					<tr>
						<td class="info">住所</td>
						<td class="text-left"><%= @customer.residence %></td>
					</tr>
					<tr>
						<td class="info">電話番号</td>
						<td class="text-left"><%= @customer.phone_number %></td>
					</tr>
					<tr>
						<td class="info">メールアドレス</td>
						<td class="text-left"><%= @customer.email %></td>
					</tr>
				</tbody>
			</table>

			<div class="mypage-bottoms">
				<P><strong class="shipping-link">配送先</strong>
					<%= link_to " 一覧を見る", customers_shipping_addresses_path, data: {"turbolinks" => false}, class: "glyphicon glyphicon-folder-open btn btn-info" %>
				</p>
				<p><strong class="order-link">注文履歴</strong>
					<%= link_to " 一覧を見る", customers_orders_path, class: "glyphicon glyphicon-folder-open btn btn-info" %>
				</p>
			</div>
	</div>
</div>