config/routes.rb
Rails.application.routes.draw do

  # admin
  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :products,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'products#top'
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

   # customer
   devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
   }

  get 'about' => 'customer/products#about'
  root 'customer/products#top'
  get 'contact' => 'customer/customers#contact'

  scope module: :customer do
    resources :products,only: [:index,:show]
    get 'search' => 'products#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :shipping_addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
	end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:residence,:phone_number,:email,:is_valid)
	end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
  		@orders = Order.all.page(params[:page]).per(10)
	end

  def current_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render :index
  end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:order_status)
	end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  include ApplicationHelper

  before_action :set_cart_item, only: [:update, :destroy]
  before_action :authenticate_customer!

  def index
    @cart_items = current_cart
  end

	def update
    @cart_item.update(quantity: params[:cart_item][:quantity].to_i)
    flash.now[:success] = "#{@cart_item.product.name}の数量を変更しました"
    @price = sub_price(@cart_item).to_s(:delimited)
    @cart_items = current_cart
    @total = total_price(@cart_items).to_s(:delimited)
    # redirect_to customers_cart_items_path
	end

	def create
    @cart_item = current_customer.cart_items.new(params_cart_item)

      # カートの中に同じ商品が重複しないようにして　古い商品と新しい商品の数量を合わせる
    @update_cart_item =  CartItem.find_by(product: @cart_item.product)
    if @update_cart_item.present? && @cart_item.valid?
        @cart_item.quantity += @update_cart_item.quantity
        @update_cart_item.destroy
    end

    if @cart_item.save
      flash[:notice] = "#{@cart_item.product.name}をカートに追加しました"
      redirect_to products_path
    else
      @product = Product.find(params[:cart_item][:product_id])
      @cart_item = CartItem.new
      flash[:alert] = "個数を選択してください"
      render ("customer/products/show")
    end
	end

	def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:alert] = "カートの商品を全て削除しました"
    redirect_to customers_cart_items_path
	end

	def destroy
    @cart_item.destroy
    flash.now[:alert] = "#{@cart_item.product.name}を削除しました"
    @cart_items = current_cart
    @total = total_price(@cart_items).to_s(:delimited)
    # respond_to do |format|
    #   format.html{ redirect_to customers_cart_items_path }
    #   format.js
    # end
    # redirect_to customers_cart_items_path
	end

  private

  def params_cart_item
    params.require(:cart_item).permit(:quantity, :product_id)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController

  before_action :authenticate_customer!, except: [:contact]

  def show
    @customer = current_customer
	end

	def quit
	end

	def out
    @customer = current_customer
    @customer.update(is_valid: true)

    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
	end

	def edit
    @customer = current_customer
	end

	def update
    @customer = current_customer
		if @customer.update(customer_params)
       flash[:success] = "登録情報を変更しました"
       redirect_to customers_path
    else
       render :edit and return
    end
	end

  def contact
  end

	private

	def customer_params
  	params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :postal_code, :residence, :phone_numbar)
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  include ApplicationHelper

  before_action :to_log, only: [:show]
  before_action :authenticate_customer!

  def new
  	@order = Order.new
  	@shipping_addresses = ShippingAddress.where(customer: current_customer)
	end

	def log
    @cart_items = current_cart
		@order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method]
    )

    # total_priceに請求額を代入
    @order.total_price = billing(@order)

    # addressにresidenceの値がはいっていれば
    if params[:order][:addresses] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.residence
      @order.name        = current_customer.last_name +
                           current_customer.first_name

    # addressにshipping_addressesの値がはいっていれば
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = ShippingAddress.find(params[:order][:shipping_address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
    elsif params[:order][:addresses] == "new_address"
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
      unless @order.valid? == true
        @shipping_addresses = ShippingAddress.where(customer: current_customer)
        render :new
      end
    end
	end

	def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to thanx_customers_orders_path

    # もし情報入力でnew_addressの場合ShippingAddressに保存
    if params[:order][:ship] == "1"
      current_customer.shipping_address.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    @cart_items = current_cart
    @cart_items.each do |cart_item|
    OrderDetail.create(
      product:  cart_item.product,
      order:    @order,
      quantity: cart_item.quantity,
      subprice: sub_price(cart_item)
    )
    end
    # 注文完了後、カート商品を空にする
    @cart_items.destroy_all
	end

	def thanx
	end

	def index
    @orders = current_customer.orders
	end

	def show
	  @order = Order.find(params[:id])
    @order_details = @order.order_details
	end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def to_log
    redirect_to customers_cart_items_path if params[:id] == "log"
  end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController

  before_action :authenticate_customer!, only: [:show]

  def top
    @products = Product.all.order(created_at: :asc)
    #=> :asc,古い順 :desc,新しい順　
    @genres = Genre.all
	end

	def index
    @genres = Genre.all
    @products = Product.where(is_sale: true).page(params[:page]).per(8)
	end

	def show
    @products = Product.all
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
	end

  def about
  end

	private
	def product_params
		parmas.require(:product).permit(:image ,:name, :explanation, :tax_out_price, :is_sale)
	end
  
end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController

  before_action :authenticate_customer!

  def index
  	@shipping_addresses = current_customer.shipping_address
  	@shipping_address = ShippingAddress.new
	end

	def create
	  @shipping_address = ShippingAddress.new(shipping_address_params)
	  @shipping_address.customer_id = current_customer.id
    @shipping_addresses = current_customer.shipping_address
	  if @shipping_address.save
	  	 flash.now[:notice] = "新規配送先を登録しました"
	     # redirect_to customers_shipping_addresses_path
	  # else
	  # 	 @shipping_addresses = current_customer.shipping_address
	  #    render 'index'
    end
	end

	def edit
    @shipping_address = ShippingAddress.find(params[:id])
	end

	def update
	  @shipping_address = ShippingAddress.find(params[:id])
	  if @shipping_address.update(shipping_address_params)
  	 flash[:success] = "配送先を変更しました"
     redirect_to customers_shipping_addresses_path
	  else
	   render "edit"
	  end
	end

	def destroy
	  @shipping_address = ShippingAddress.find(params[:id])
	  @shipping_address.destroy
    @shipping_addresses = current_customer.shipping_address
    flash.now[:alert] = "配送先を削除しました"
	  # redirect_to customers_shipping_addresses_path
	end

	private

	def shipping_address_params
  	params.require(:shipping_address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :authenticate_customer!, only: [:edit, :update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
     # @customer = current_customer
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      # respond_with resource, location: after_update_path_for(resource)
      flash[:success] = "パスワード変更しました。"
      redirect_to customers_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to customers_path
      flash[:alert] = "パスワードを変更できませんでした。"
    end
    # super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def customer_params
    params.require(:customers).permit(:password, :password_confirmation)
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation])
  # end

  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  def after_update_path_for(resource)
    customers_path(resource)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController

    before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_customer_session_path
      end
    else
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>
<div calss="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
      <% if @orders.present? %>
        <table class="table table-hover table-bordered table-condensed">
          <thead>
            <tr class="info">
              <th><i class="fas fa-calendar-day"></i>注文日</th>
              <th>配送先</th>
              <th>注文商品</th>
              <th>支払金額</th>
              <th>ステータス</th>
              <th>注文詳細</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
    		          <%= order.created_at.strftime('%Y/%m/%d') %>
    		        </td>
    		        <td class="text-left">
    		          <%= order.postal_code %><br>
    		          <%= order.address %><br>
    		          <%= order.name %>
    		        </td>
    		        <td>
    		          <% order.order_details.each do |order_detail| %>
    		          	<%= order_detail.product.name %><br>
    		          <% end %>
    		        </td>
    		        <td class="text-right">
    		          <%= order.total_price.to_s(:delimited) %>円
    		        </td>
    		        <td>
    		          <%= order.order_status %>
    		        </td>
         	      <td>
       	          <%= link_to "注文詳細", customers_order_path(order), class: "glyphicon glyphicon-zoom-in btn btn-success" %>
       	        </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>注文履歴がありません。</p>
      <% end %>
    </div>
</div>

app/views/customer/orders/log.html.erb
<% provide(:title, "注文情報確認") %>
<h2 class="head-line title_h2 text-center">注文情報確認</h2>
<div calss="row">
  <div class="col-xs-9">
    <% if current_customer.cart_items.present? %>
      <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |cart| %>
            <tr>
              <td class="text-left">
                <%= attachment_image_tag( cart.product, :image, size: "60x50", fallback: "no_image.jpg") %>
                <%= cart.product.name %>
              </td>
              <td class="text-right">
                ¥<%= tax_price(cart.product.tax_out_price).to_s(:delimited) %>
              </td>
              <td class="text-right">
                  <%= cart.quantity %>
              </td>
              <td class="text-right">
                ¥<%= sub_price(cart).to_s(:delimited) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-3 billing">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">送料</th>
            <td class="text-right col-xs-5">¥<%= @order.postage %></td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-right">¥<%= total_price(@cart_items).to_s(:delimited) %></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-right">¥<%= billing(@order).to_s(:delimited) %></td>
          </tr>
      </table>
    </div>
    <div class="col-xs-9 billing">
      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= @order.payment_method %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= "#{@order.postal_code} #{@order.address} 　#{@order.name}" %>
          </td>
        </tr>
      </table>

      <!-- 表示とformを分けて記入 -->
      <div class ="col-xs-11">
      <%= form_with model: @order, url: customers_orders_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :postal_code %>
        <%= f.hidden_field :address %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :payment_method %>
        <%= f.hidden_field :total_price %>
        <%= f.hidden_field :ship, value: @ship %>
        <%= link_to "注文情報入力へ戻る", new_customers_order_path, data: {"turbolinks" => false}, class: "btn btn-info col-xs-3 back" %>
        　　<i class="fas fa-shipping-fast fa-2x"></i>
        <%= f.submit "購入を確定する", class: "btn btn-warning center-block col-xs-5" %>
      <% end %>
      </div>
    <% else %>
        <!-- if カートアイテムがない時 -->
        <p>お客様のショッピングカートに商品はありませんので注文確定ができません。</p>
        <p><%= link_to "商品一覧", products_path %>から商品をお探し下さい。</p>
    <% end %>
  </div>
</div>

app/views/customer/orders/new.html.erb
<% provide(:title, "注文情報入力") %>
<div class="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">注文情報入力</h2>
    <% if current_customer.cart_items.present? %>

    <%= render "layouts/error_messages", resource: @order%>
    <div class="col-xs-offset-1">
      <%= form_with :model => @order, url:log_customers_orders_path, method: :post, local: true  do |f| %>
        <h3 class="col-xs-3 sub-head text-center"><i class="fas fa-yen-sign"></i>支払い方法</h3>
          <div class="col-xs-10 radio">
            <%= f.radio_button :payment_method, :"クレジットカード", checked: true %>
            <span>&nbsp;クレジットカード</span>
          </div>
          <div class="col-xs-10 radio">
            <%= f.radio_button :payment_method, :"銀行振込" %>
            <span>&nbsp;銀行振り込み</span>
          </div>

        <h3 class="col-xs-3 sub-head text-center"><i class="fas fa-people-carry"></i>お届け先</h3>
          <div class="col-xs-10 radio">
            <%= f.radio_button :addresses, "residence", checked: true  %>
            <span>&nbsp;ご自身の住所</span><br>
            &emsp;&emsp;<%= "#{current_customer.postal_code} #{current_customer.residence}" %>
            <br>
            &emsp;&emsp;<%= "#{current_customer.first_name} #{current_customer.last_name}" %>
          </div>

          <% if @shipping_addresses != [] %>
          <div class="col-xs-10 radio">
            <%= f.radio_button :addresses, "shipping_addresses" %>
              <span>&nbsp;登録済住所から選択</span><br>
              <!-- order_addressはshipping_addressのモデルでpostal_code+address+name -->
            &emsp;&emsp;<%= f.collection_select(:shipping_address_id, @shipping_addresses, :id, :order_address) %>
          </div>
          <% end %>

          <div class="new-address col-xs-10 radio">
            <%= f.radio_button :addresses, "new_address" %>
            <span>&nbsp;新しいお届け先</span><br>
            <div class="field form-group col-xs-11">
              <%= f.label :"郵便番号(ハイフンなし)", class: "col-sm-4 control-label" %>
              <%= f.text_field :postal_code, class: "col-sm-3 form-control-static postal_code" %>
            </div>
            <div class="field form-group col-xs-11">
              <%= f.label :"住所", class: "col-sm-4 control-label" %>
              <%= f.text_field :address, class: "col-sm-8 form-control-static address" %>
            </div>
            <div class="field form-group col-xs-11">
              <%= f.label :"宛名", class: "col-sm-4 control-label" %>
              <%= f.text_field :name, class: "col-sm-4 form-control-static" %>
            </div>
          </div>

          <div class="btns col-xs-8">
            <%= link_to customers_cart_items_path, class: "glyphicon glyphicon-shopping-cart btn btn-info col-xs-3 cart-back" do %>
             カート(<%= current_customer.cart_items.count %>)へ戻る
            <% end %>
            <%= f.submit "確認画面へ進む", class: "btn btn-success col-xs-5" %>
          </div>
      <% end %>
    </div>
    <% else %>
      <!-- if カートアイテムがない時 -->
      <p>お客様のショッピングカートに商品はありませんので注文情報の入力ができません。</p>
      <p><%= link_to "商品一覧", products_path, class: "btn btn-warning" %>から商品をお探し下さい。</p>
    <% end %>
  </div>
</div>

app/views/customer/orders/show.html.erb
<% provide(:title, "注文履歴詳細") %>
<h2 class="head-line title_h2 text-center">注文履歴詳細</h2>
<div calss="row">
  <% if @order.present? %>
    <div class="col-xs-8">
    	<strong><i class="far fa-user"></i>注文情報</strong>
  	    <table class="table table-bordered table-condensed">
          <tbody>
              <tr>
                <th class="info">注文日</th>
          	  <td class="text-left"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
              </tr>
              <tr>
              　<th class="info">配送先</th>
                <td class="text-left"><%= @order.postal_code %><br>
                	  <%= @order.address %><br>
                	  <%= @order.name %>
                </td>
              </tr>
              <tr>
              　<th class="info">支払方法</th>
                <td class="text-left"><%= @order.payment_method %></td>
              </tr>
              <tr>
                <th class="info">ステータス</th>
                <td class="text-left"><%= @order.order_status %></td>
              </tr>
          </tbody>
        </table>
    </div>

    <div class="col-xs-3 col-xs-offset-1 billing">
      <strong><i class="fas fa-yen-sign"></i>請求情報</strong>
        	<table class="table  table-bordered table-condensed">
            <tr>
              <th class="info">商品合計</th>
              <td class="text-right col-xs-5"><%= total_price(@order_details).to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th class="info">配送料</th>
              <td class="text-right col-xs-5"><%= @order.postage.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th class="info">ご請求金額</th>
              <td class="text-right col-xs-5"><%= @order.total_price.to_s(:delimited) %>円</td>
            </tr>
        </table>
    </div>
    <div class="col-xs-7 order-details">
    	<strong><i class="fas fa-store"></i>注文内容</strong>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
  	      <tr class="info">
  	      	<th>商品</th>
  	        <th>単価(税込)</th>
  	      	<th>個数</th>
  	      	<th>小計</th>
  	      </tr>
        	</thead>
        	<tbody>
        	<% @order_details.each do |order_detail| %>
            <tr>
  	        <td><%= order_detail.product.name %></td>
  	        <td class="text-right"><%= tax_price(order_detail.product.tax_out_price).to_s(:delimited) %>円</td>
  	        <td class="text-right"><%= order_detail.quantity %></td>
  	        <td class="text-right"><%= sub_price(order_detail).to_s(:delimited) %>円</td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>
    <% if customer_signed_in? %>
      <%= link_to "注文履歴一覧へ戻る", customers_orders_path, class: "btn btn-info btn-lg order-index-back" %>
    <% else %>
      <%= link_to "会員詳細へ戻る", admin_customer_path, class: "btn btn-info order-index-back" %>
    <% end %>
  <% else %>
    <p>注文履歴がありません。</p>
  <% end %>
</div>

app/views/customer/orders/thanx.html.erb
<% provide(:title, "ありがとうございました！") %>
<div class="row col-xs-12 center-block">
  <h1 class="text-center thanx">ご購入ありがとうございました！</h1><br>
  <div class="col-xs-7">
    <%= link_to "　注文履歴はこちら　", customers_orders_path, class: "glyphicon glyphicon-folder-open btn btn-info pull-right" %>
  </div>
</div>

app/views/customer/orders/thenx.html.erb
<p>ご購入ありがとうございました！</p>