config/routes.rb
Rails.application.routes.draw do

  # admin
  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :products,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'products#top'
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

   # customer
   devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
   }

  get 'about' => 'customer/products#about'
  root 'customer/products#top'
  get 'contact' => 'customer/customers#contact'

  scope module: :customer do
    resources :products,only: [:index,:show]
    get 'search' => 'products#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :shipping_addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :customer
	has_many :order_details, dependent: :destroy

	validates :customer_id, :address,:name, :postage,
			  		:total_price, :payment_method,
			  		presence: true
	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
	validates :postage, :total_price, numericality: { only_integer: true }

	enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
	enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
  		@orders = Order.all.page(params[:page]).per(10)
	end

  def current_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render :index
  end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:order_status)
	end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  include ApplicationHelper

  before_action :to_log, only: [:show]
  before_action :authenticate_customer!

  def new
  	@order = Order.new
  	@shipping_addresses = ShippingAddress.where(customer: current_customer)
	end

	def log
    @cart_items = current_cart
		@order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method]
    )

    # total_priceに請求額を代入
    @order.total_price = billing(@order)

    # addressにresidenceの値がはいっていれば
    if params[:order][:addresses] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.residence
      @order.name        = current_customer.last_name +
                           current_customer.first_name

    # addressにshipping_addressesの値がはいっていれば
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = ShippingAddress.find(params[:order][:shipping_address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
    elsif params[:order][:addresses] == "new_address"
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
      unless @order.valid? == true
        @shipping_addresses = ShippingAddress.where(customer: current_customer)
        render :new
      end
    end
	end

	def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to thanx_customers_orders_path

    # もし情報入力でnew_addressの場合ShippingAddressに保存
    if params[:order][:ship] == "1"
      current_customer.shipping_address.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    @cart_items = current_cart
    @cart_items.each do |cart_item|
    OrderDetail.create(
      product:  cart_item.product,
      order:    @order,
      quantity: cart_item.quantity,
      subprice: sub_price(cart_item)
    )
    end
    # 注文完了後、カート商品を空にする
    @cart_items.destroy_all
	end

	def thanx
	end

	def index
    @orders = current_customer.orders
	end

	def show
	  @order = Order.find(params[:id])
    @order_details = @order.order_details
	end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def to_log
    redirect_to customers_cart_items_path if params[:id] == "log"
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>
<h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<table class="table table-hover table-bordered table-condensed">
		  <thead>
		    <tr class="info">
		      <th class="col-xs-3"><i class="far fa-clock"></i>購入日時</th>
	      	  <th><i class="far fa-user"></i>購入者</th>
		      <th class="col-xs-1">注文個数</th>
		      <th class="col-xs-2">注文ステータス</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @orders.each do |order| %>
		      <tr>
		        <td>
		          <%= link_to admin_order_path(order), data: {"turbolinks" => false}, :style=>"color:#528fff;"  do %>
		          	<%= order.created_at %>
		          <% end %>
		        </td>
		        <td class="text-left">
		          <%= full_name(order.customer) %>
		        </td>
		        <td class="text-right">
		          <%= order.order_details.count %>
		        </td>
    	        <td>
    	      	  <%= order.order_status %>
     	        </td>
     	      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
    <div class="text-center"><%= paginate(@orders) %></div>
</div>

app/views/admin/orders/show.html.erb
<% provide(:title, "注文履歴詳細") %>
<h2 class="head-line title_h2 text-center">注文履歴詳細</h2>
  <div class="row">
    <div class="col-xs-12" >
      <div class="col-xs-9">
		<div class="field">
		  <div class="col-xs-4">
			購入者
		  </div>
		  <div class="col-xs-8">
		    <%= @order.name %>
		  </div>
		</div>

	    <div class="field">
	      <div class="col-xs-4">
	        配送先
	      </div>
	      <div class="col-xs-8">
	        <%= full_address(@order) %>
	      </div>
	    </div>

	    <div class="field">
	      <div class="col-xs-4">
	        支払い方法
	      </div>
	      <div class="col-xs-8">
	        <%= @order.payment_method %>
	      </div>
	    </div>

 	  <%= form_for(@order, url: admin_order_path, method: :patch) do |f| %>
 	    <div class="col-xs-4">注文ステータス</div>
      	  <div class="col-xs-6">
            <%= f.select :order_status, Order.order_statuses.keys, class: "order_status" %>
          </div>

      	<div class="actions">
          <div class="col-xs-2"><%= f.submit '更新'  ,class: "btn btn-primary" %></div>
      	</div>
      <% end %>
      </div>

	  <div class="buyer-order col-xs-9">
			<table class="table table-hover table-bordered table-inverse">
			    <thead>
			        <tr class="info">
			          <th class="col-xs-4">商品名</th>
			          <th>単価（税込）</th>
			          <th>数量</th>
			          <th>小計</th>
			          <th>製作ステータス</th>

			        </tr>
			    </thead>
				<tbody>
				<% if flash[:notice] %>
		          	<div class="flash">
		             <%= flash[:notice] %>
		          	</div>
	          	<% end %>
				<% @order_details.each do |order_detail| %>
					<tr>
			            <td class="text-left">
			              <%= order_detail.product.name %>
			            </td>
			            <td class="text-right">
			              ¥<%= tax_price(order_detail.product.tax_out_price).to_s(:delimited) %>
			            </td>
			            <td class="text-right">
			              <%= order_detail.quantity %>
			            </td>
			            <td class="text-right">
			              ¥<%= sub_price(order_detail).to_s(:delimited) %>
			            </td>
			            <%= form_for(order_detail, url: admin_order_details_path(order_detail), method: :patch) do |f| %>
			            <td>
			            	<%= f.select :produciton_status, OrderDetail.produciton_statuses.keys, class: "order_status" %>
			            	<%= f.submit '更新'  ,class: "btn btn-warning" %>
			            </td>
			            <% end %>
			      	</tr>
				<% end %>
				</tbody>
			</table>
	  </div>

	  <div class="col-xs-3  billing">
			<table class="table table-hover table-bordered table-condensed">
				<tr>
            		<th class="info">商品合計</th>
					<td>¥<%= total_price(@order_details).to_s(:delimited) %></td>
				</tr>
				<tr>
					<th class="info">送料</th>
					<td>¥<%= @order.postage.to_s(:delimited) %></td>
				</tr>
				<tr>
					<th class="info">請求金額合計</th>
					<td>¥<%= @order.total_price.to_s(:delimited) %></td>
				</tr>
		    </table>
	  </div>
    <div class="col-xs-12">
      <%= link_to "戻る", admin_orders_path, class: "glyphicon glyphicon-home btn btn-info" %>
    </div>
	  </div>
  </div>