config/routes.rb
Rails.application.routes.draw do

  # admin
  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :products,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'products#top'
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

   # customer
   devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
   }

  get 'about' => 'customer/products#about'
  root 'customer/products#top'
  get 'contact' => 'customer/customers#contact'

  scope module: :customer do
    resources :products,only: [:index,:show]
    get 'search' => 'products#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :shipping_addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord

	belongs_to :genre
	has_many :cart_items
	has_many :orders, through: :order_details
	has_many :order_details

	attachment :image

	validates :genre_id, :name, :tax_out_price, presence: true
	validates :explanation, length: {maximum: 200}
	validates :tax_out_price, numericality: { only_integer: true }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update]
  before_action :set_genres, only: [:new, :edit, :index, :create, :update]
  before_action :authenticate_admin!

  def top
    now = Time.current
    @orders = Order.where(created_at: now.all_day)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "新商品を登録しました"
      redirect_to admin_product_path(@product)
    else
      render :new
    end
  end

  def index
    @products = Product.all.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = "商品内容をを変更しました"
      redirect_to admin_product_path(@product)
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :image, :explanation,
       :genre_id, :tax_out_price, :is_sale)
  end

  def set_genres
    @genres = Genre.where(is_valid: true)
  end
  
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController

  before_action :authenticate_customer!, only: [:show]

  def top
    @products = Product.all.order(created_at: :asc)
    #=> :asc,古い順 :desc,新しい順　
    @genres = Genre.all
	end

	def index
    @genres = Genre.all
    @products = Product.where(is_sale: true).page(params[:page]).per(8)
	end

	def show
    @products = Product.all
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
	end

  def about
  end

	private
	def product_params
		parmas.require(:product).permit(:image ,:name, :explanation, :tax_out_price, :is_sale)
	end
  
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/admin/products/_form_product.html.erb
<div class="form-group">
  <%= f.label :"商品名", class: "col-sm-3 control-label" %>
  <%= f.text_field :name, class: "col-sm-9 form-control-static name" %>
</div>
<div class="form-group">
  <%= f.label :"商品説明", class: "col-sm-3 control-label" %>
  <%= f.text_area :explanation, class: "col-sm-9 control-label explanation" %>
</div>
<div class="form-group">
  <%= f.label :"ジャンル", class: "col-sm-3 control-label" %>
  <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --", class: "col-sm-9 genre_id") %>
</div>
<div class="form-group">
  <%= f.label :"税抜価格", class: "col-sm-3 control-label" %>
  <%= f.text_field :tax_out_price, class: "col-sm-3 form-control-static tax_out_price" %>円
</div>
<div class="form-group">
  <%= f.label :"販売ステータス", class: "col-sm-3 control-label" %>
  <%= f.select :is_sale, [['販売中', true], ['販売停止', false]], prompt: "-- 選択してください --", class: "col-sm-9 is_sale" %>
</div>

app/views/admin/products/edit.html.erb
<% provide(:title, "商品編集") %>
<h2 class="head-line title_h2 text-center">商品編集</h2>
<div class="row">

  <%= form_for(@product, url: admin_product_path, method: :patch, class: "form-horizontal") do |f| %>
    <%= render "layouts/error_messages", resource: @product%>
    <div class="col-xs-4">
      <div class="img_field">
        <%= attachment_image_tag(@product, :image, size: "250x180") %>
      </div>
      <div class="form-group">
	      <%= f.attachment_field :image, class: " image" %>
      </div>
    </div>

    <div class="col-xs-6">
      <%= render "form_product", f: f %>
      <div class="actions">
	      <%= f.submit "変更を保存", class: "btn btn-primary pull-right" %>
      </div>

    </div>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<% provide(:title, "商品一覧") %>
<h2 class="head-line title_h2 text-center admin_product_index">商品一覧</h2>
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <%= link_to new_admin_product_path, data: {"turbolinks" => false}, class: "btn btn-warning pull-right new_product" do %>
    <i class="fas fa-plus"></i>
    新規商品登録
    <% end %>
    <table class="table table-hover table-bordered table-condensed">
      <thead>
        <tr class="info">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
				<% @products.each do |product| %>
  				<tr>
            <td class="info col-xs-1">
              <%= product.id %>
            </td>
            <td class="text-left">
              <%= link_to admin_product_path(product), class: "btn-link" do %>
                <%= product.name %>
              <% end %>
            </td>
            <td class="text-right col-xs-1">
              ¥<%= product.tax_out_price.to_s(:delimited) %>
            </td>
            <td class="text-left col-xs-3">
              <%= product.genre.name %>
            </td>
            <td class="col-xs-2">
              <% if product.is_sale == true %>
      					<p><i class="fas fa-bullseye red"></i>販売中</p>
      				<% elsif product.is_sale == false %>
      					<p><i class="fas fa-bullseye blue"></i>販売停止中</p>
      				<% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <div class="text-center"><%= paginate(@products) %></div>
</div>

app/views/admin/products/new.html.erb
<% provide(:title, "商品新規登録") %>

<div class="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">商品新規登録</h2>
    <%= form_for(@product, url: admin_products_path, method: :post, class: "form-horizontal") do |f| %>
      <%= render "layouts/error_messages", resource: @product %>
      <div class="col-xs-4 col-xs-offset-1">
        <div class="img_field">
        </div>
  	      <%= f.attachment_field :image, class: "image" %>
      </div>
      <div class="col-xs-6">
        <%= render "form_product", f: f %>
        <div class="actions col-xs-7">
  	      <%= f.submit "新規登録", class: "btn btn-primary btn-lg pull-right" %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<% provide(:title, "商品詳細") %>
<h2 class="head-line title_h2 text-center">商品詳細</h2>
<div class="row">
	<div class="col-xs-12">
	  <div class="col-xs-4">
	      <div id="img_field">
	          <%= attachment_image_tag(@product, :image, size: "300x220", fallback: "no_image.jpg") %>
	      </div>
      </div>
      <div class="col-xs-6">
	      <div class="field">
					<p>
						商品名　　　　　<%= @product.name %>
					</p>
	      </div><br>
	      <div class="field">
					<p>
						商品説明　　　　<%= @product.explanation %>
					</p><br>
	      </div>
	      <div class="field">
					<p>
						ジャンル　　　　<%= @product.genre.name %>
					</p><br>
	      </div>
	      <div class="field">
					<p>
						税込価格　　　　<%= tax_price(@product.tax_out_price).to_s(:delimited) %>
	        								(<%= @product.tax_out_price.to_s(:delimited) %>) 円<br>
						(税抜価格)
					</p><br>
	      </div>
	      <div class="field">
					<p>
						販売ステータス
		        <% if @product.is_sale == true %>
							　<i class="fas fa-bullseye red"></i>販売中
						<% elsif @product.is_sale == false %>
							　<i class="fas fa-bullseye blue"></i>販売停止中
						<% end %>
					</p>
	      </div>
		  <div class="actions col-xs-9">
	      		<%= link_to "編集する", edit_admin_product_path(@product), data: {"turbolinks" => false}, class: "glyphicon glyphicon-pencil btn btn-success pull-right" %>
      	  </div>
      	</div>
    </div>
</div>

app/views/admin/products/top.html.erb
<% provide(:title, "トップ") %>
<div class="row">
	<div class="col-xs-12">
		<h2 class="head-line title_h2 text-center">管理者画面</h2>
		<p class="order-count">本日の注文件数
			<span>
				<%= link_to today_order_index_admin_orders_path, class: "btn-link" do %> 
				<%= @orders.count %>件
				<% end %>
			</span>
		</p>
	</div>
</div>